CREATE TABLE IF NOT EXISTS contact(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR(20) NOT NULL,
FOREIGN KEY (CompanyId) REFERENCES company(Id),
FOREIGN KEY (CountryId) REFERENCES country(Id)
);

SELECT * FROM contact;

CREATE TABLE IF NOT EXISTS company(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR(20) NOT NULL,
FOREIGN KEY (ContactId) REFERENCES contact(Id)
);

CREATE TABLE IF NOT EXISTS country(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL,
FOREIGN KEY (ContactId) REFERENCES contact(Id)
);

CREATE TABLE IF NOT EXISTS employee(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Firstname VARCHAR(20) NOT NULL,
Lastname VARCHAR(20) NOT NULL,
Gender ENUM ("m", "f"),
Address VARCHAR(20) NOT NULL,
Birthdate DATE NOT NULL,
Employmentdate DATE NOT NULL,
Leavingdate DATE NOT NULL,
Details TEXT NOT NULL
);
